trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'veil'
      api_location: 'veil/build/server'
      output_location: 'build/static'
      azure_static_web_apps_api_token: $(deployment_token)