name: Granary - build, test & deployment.

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'feature/**'
    paths:
      - 'granary/**'
      - '.github/workflows/granary.yml'
env:
  AZURE_WEBAPP_NAME: granary
  AZURE_WEBAPP_PACKAGE_PATH: 'deploy'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: 'Build & test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - name: Setup tailwind
        shell: bash
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
          ./tailwindcss -i wwwroot/css/site.css -o wwwroot/css/app.css --minify
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}
        
      - name: Restore
        run: dotnet restore          
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Publish
        run: dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: '${{ env.AZURE_WEBAPP_NAME }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
    
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Install Az SWA CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy App
        run: |
          swa deploy dist/wwwroot --deployment-token ${{ secrets.AZURE_SWA_GRANARY_TOKEN }} -name granary
