name: listingApp - build & test

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'feature/**'
    paths:
      - 'granary/**'

jobs:
  build:
    name: 'Build - listingApp'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tailwind
        shell: bash
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
          ./tailwindcss -i wwwroot/styles/site.css -o wwwroot/styles/app.css --minify
        working-directory: granary

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: granary

      - name: Build
        run: dotnet build --no-restore
        working-directory: granary
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: granary