name: Granary - build, test & deployment.

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'feature/**'
    paths:
      - 'granary/**'
      - '.github/workflows/granary.yml'
env:
  AZURE_WEBAPP_NAME: granary
  AZURE_WEBAPP_PACKAGE_PATH: 'deploy'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: 'Build & test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - name: Setup tailwind
        shell: bash
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
          ./tailwindcss -i wwwroot/styles/site.css -o wwwroot/styles/app.css --minify
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}
        
      - name: Restore
        run: dotnet restore          
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Publish
        run: dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
        working-directory: ${{ env.AZURE_WEBAPP_NAME }}            
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_NAME }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
   #if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: deploy-app

      - name: 'Azure Login'    
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: 'Run Azure webapp deploy action using Azure Credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: 'deploy-app'
          
      - name: 'Azure Logout'
        run: az logout
