name: Granary - build, test & deployment.

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'feature/**'
    paths:
      - 'granary/**'
env:
  AZURE_WEBAPP_NAME: granary
  AZURE_WEBAPP_PACKAGE_PATH: 'granary'
  DOTNET_VERSION: '8.0.x'
  
jobs:
  build:
    name: 'Build & test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - name: Setup tailwind
        shell: bash
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
          ./tailwindcss -i wwwroot/styles/site.css -o wwwroot/styles/app.css --minify
        working-directory: granary
        
      - name: Restore
        run: dotnet restore          
        working-directory: granary

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: granary
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: granary

      - name: Publish
        run: dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}' 
        working-directory: granary            
      
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
   #if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Run Azure webapp deploy action using Azure Credentials'
        uses: azure/webapps-deploy@v3
        if: github.ref == 'refs/heads/main'
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}'
      
      - name: logout
        run: az logout
